name: Automatically fork upstream repository

on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 */1 * * *
    # 每隔1小时执行一次
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.FORK_TOKEN }} # 令牌，需要开启仓库权限
          upstream_repository: TBXark/ChatGPT-Telegram-Workers  # 上游仓库
          target_repository: ${{ secrets.YOUR_repository }}  # 你的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: master  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
